version: '3'
services:
  web:
    image: docker-com.lohika.jclub.oauth2-spring
    ports:
      - "8080:8080"
    environment:
      - AUTH_HOST=auth
#      - SECURITY_OAUTH2_CLIENT_USERAUTHORIZATIONURI=http://auth:8081
#      - SECURITY_OAUTH2_CLIENT_ACCESSTOKENURI=http://auth:8081
#      - SECURITY_OAUTH2_CLIENT_USERINFOURI=http://auth:8081/me
    links:
      - auth
  auth:
    image: docker-com.lohika.jclub.oauth2-auth-server
    ports:
      - "8081:8081"
#    links:
#      - web
#    depends_on:
#      - web
#    environment:
#      - WEB_HOST=web
#      - SECURITY_OAUTH2_CLIENT_PREESTABLISHEDREDIRECTURI=http://web:8080